import crypto from "crypto";
import fs from "fs";
import path from "path";
import webpush from "web-push";

// Path for persisting generated secrets across container restarts.
// In Docker, this must point to a path on a named volume.
// The API container's working directory is /app, but we write to /app/.env.generated
// which can be persisted via a bind mount or volume.
const GENERATED_ENV_PATH =
  process.env.GENERATED_ENV_PATH ||
  path.join(process.cwd(), ".env.generated");

/**
 * Load previously generated secrets from .env.generated if it exists.
 * This runs BEFORE the missing-secret checks so that generated values
 * survive container restarts even if they were not added to .env.
 */
function loadGeneratedSecrets(): void {
  if (!fs.existsSync(GENERATED_ENV_PATH)) {
    return;
  }

  try {
    const content = fs.readFileSync(GENERATED_ENV_PATH, "utf-8");
    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx === -1) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      const value = trimmed.slice(eqIdx + 1).trim();
      // Only set if not already set — explicit .env values take precedence.
      if (key && value && !process.env[key]) {
        process.env[key] = value;
      }
    }
  } catch (err) {
    console.warn("[secrets] Could not read .env.generated:", err);
  }
}

/**
 * Persist newly generated secrets to .env.generated so they survive
 * container restarts. Merges with any existing content.
 */
function persistSecrets(generated: Record<string, string>): void {
  if (Object.keys(generated).length === 0) return;

  // Read existing content to merge
  let existing: Record<string, string> = {};
  if (fs.existsSync(GENERATED_ENV_PATH)) {
    try {
      const content = fs.readFileSync(GENERATED_ENV_PATH, "utf-8");
      for (const line of content.split("\n")) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith("#")) continue;
        const eqIdx = trimmed.indexOf("=");
        if (eqIdx === -1) continue;
        const key = trimmed.slice(0, eqIdx).trim();
        const value = trimmed.slice(eqIdx + 1).trim();
        if (key && value) existing[key] = value;
      }
    } catch {
      // start fresh if unreadable
    }
  }

  const merged = { ...existing, ...generated };
  const lines = [
    "# Auto-generated by dead-letter-diary on first boot",
    "# DO NOT edit manually. Add secrets to .env instead.",
    "",
    ...Object.entries(merged).map(([k, v]) => `${k}=${v}`),
  ];

  try {
    fs.writeFileSync(GENERATED_ENV_PATH, lines.join("\n") + "\n", "utf-8");
  } catch (err) {
    // Non-fatal — secrets are still in process.env for this run.
    console.warn(
      "[secrets] Could not write .env.generated (read-only filesystem?):",
      err
    );
  }
}

/**
 * Ensure all required secrets exist in process.env.
 * Missing secrets are generated automatically and persisted for future boots.
 * Must be called before any auth or encryption work.
 */
export async function ensureSecrets(): Promise<void> {
  // First, load any previously generated secrets so restarts don't re-generate.
  loadGeneratedSecrets();

  const generated: Record<string, string> = {};

  // SESSION_SECRET — 256-bit random hex
  if (!process.env.SESSION_SECRET) {
    const secret = crypto.randomBytes(32).toString("hex");
    process.env.SESSION_SECRET = secret;
    generated.SESSION_SECRET = secret;
    console.log("[secrets] Generated SESSION_SECRET");
  }

  // VAPID keys — required for Web Push notifications
  if (!process.env.VAPID_PUBLIC_KEY || !process.env.VAPID_PRIVATE_KEY) {
    const vapidKeys = webpush.generateVAPIDKeys();
    process.env.VAPID_PUBLIC_KEY = vapidKeys.publicKey;
    process.env.VAPID_PRIVATE_KEY = vapidKeys.privateKey;
    generated.VAPID_PUBLIC_KEY = vapidKeys.publicKey;
    generated.VAPID_PRIVATE_KEY = vapidKeys.privateKey;
    console.log("[secrets] Generated VAPID keys");
  }

  // SHARD_ENCRYPTION_KEY — 256-bit random hex for diary shard encryption
  if (!process.env.SHARD_ENCRYPTION_KEY) {
    const key = crypto.randomBytes(32).toString("hex");
    process.env.SHARD_ENCRYPTION_KEY = key;
    generated.SHARD_ENCRYPTION_KEY = key;
    console.log("[secrets] Generated SHARD_ENCRYPTION_KEY");
  }

  // Persist any newly generated secrets
  if (Object.keys(generated).length > 0) {
    persistSecrets(generated);
    console.log(
      "[secrets] Persisted generated secrets to",
      GENERATED_ENV_PATH
    );
    console.log(
      "[secrets] IMPORTANT: Copy generated secrets to your .env file for permanent persistence."
    );
  } else {
    console.log("[secrets] All secrets present — no generation needed.");
  }
}
